stages:
  - test
  - build

build:
  image: python:3.11
  stage: build
  variables:
    PIP_DISABLE_PIP_VERSION_CHECK: "1"
    POETRY_VIRTUALENVS_IN_PROJECT: "true"
    POETRY_NO_INTERACTION: "1"
    POETRY_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pypoetry"
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    key:
      files:
        - poetry.lock
        - pyproject.toml
    paths:
      - .venv/
      - .cache/pypoetry/
      - .cache/pip/
  before_script:
    - python -V
    - pip install poetry==1.8.4
    - poetry --version
    - poetry install --no-ansi
  script:
    - poetry build
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - dist/
